# Generated by Django 4.0.3 on 2022-05-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('Semester', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='academics/Assignment')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dept', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='academics/Book')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='academics/Calender')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PYQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
                ('exam', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='academics/PYQ')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='academics/TimeTable')),
                ('date', models.DateField()),
            ],
        ),
    ]
